version: "3.9"

services:
  base-services:
    build: ./base-service
    ports:
      - "1212:1212"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PWD="123"
  redis:
    image: redis:7
    ports:
      - "6379:6379"